---
glass_breaker_group:
  - vitor
  - root

freezing_dates:
  End of the Year:
    from:  2025-12-24
    to: 2025-01-03
  Carnival:
    from: 2025-03-01
    to: 2025-03-01
  black friday:
    from: 2025-11-20
    to: 2025-11-30