---
glass_breaker_group:
  - vitor


freezing_dates:
  End of the Year:
    from:  2025-12-24
    to: 2026-01-03
  Carnival:
    from: 2025-02-28
    to: 2025-03-05
  black friday:
    from: 2025-11-20
    to: 2025-11-30
  test:
    from: 2025-09-23
    to: 2025-09-29