version: '3.6'

services:
  gitlab:
    image: gitlab/gitlab-ce:17.5.3-ce.0
    container_name: gitlab
    restart: always
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
    networks:
      - gitlab
    ports:
      - "80:80"
      - "22:22"
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    shm_size: 256m

  dind:
    container_name: dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    image: docker:dind
    privileged: true
    restart: always
    networks:
      gitlab:
        aliases:
          - docker
    ports:
      - 2376:2376
    tty: true
    volumes:
      - docker-cache:/var/lib/docker
      - certs:/certs/client

  runner:
    container_name: runner
    restart: always
    image: gitlab/gitlab-runner:alpine
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - gitlab
    volumes:
      - runner-config:/etc/gitlab-runner
      - certs:/certs/client

networks:
  gitlab:

volumes:
  config:
  docker-cache:
  logs:
  data:
  certs:
  runner-config: